apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: chartmuseum
  namespace: flux-system
spec:
  interval: 10m
  url: https://chartmuseum.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chartmuseum
  namespace: flux-system
spec:
  chart:
    spec:
      chart: chartmuseum
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    env:
      open:
        DISABLE_API: "false"
        AUTH_ANONYMOUS_GET: "true"
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: twuni
  namespace: flux-system
spec:
  interval: 10m
  url: https://helm.twun.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry
  namespace: flux-system
spec:
  chart:
    spec:
      chart: docker-registry
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
  interval: 10m0s
  timeout: 10m0s
  install:
    crds: CreateReplace
    remediation:
      retries: 3